### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by benevbright** [hagenburger/pimd#12]
We need writing basic document describing how to implement this module on HTML+Javascript project.

**Comment by hagenburger** [comment]
This documentation should be written in the `README.md` of the root folder of this project.

- [ ] Setup and installation via NPM
- [ ] Rendering of a simple Markdown project

We can discuss details via Slack.

**Comment by artnerdnet** [comment]
Hi @hagenburger @benevbright @dianavile do we have any advancements on this or should I contribute?
