### ISSUE TITLE
Fill the live demo with an useful example

### ISSUE THREAD

**Issue by hagenburger** [hagenburger/pimd#59]
When you open the live demo (#42), you should see a useful Markdown example on the left side which is already rendered on the right side. This example should include:

- Headlines of 2 different levels (`#` and `##`)
- Paragraphs with
    - Links
    - Bold text
    - Italic text
- Code blocks with
    - Syntax highlighting
    - A preview
    - Highlights in code
    - Show more
- A list
- Anything else?

The text should be written in a way that it documents its use by itself.

**Comment by artnerdnet** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fill the live demo with an useful example](https://trello.com/c/XrEIaoWI/41-fill-the-live-demo-with-an-useful-example)
