### ISSUE TITLE
Create plugin that loads all plugins

### ISSUE THREAD

**Issue by hagenburger** [hagenburger/pimd#61]
Create a new plugin in `plugins/allinc` with the package name `@pimd/allinc`. This should load all plugins you can find in `plugins/*-plugin` (in other words: all extensions to PIMD but not the Gulp integration). All plugins should be loaded with `config.use(insertPluginNameHere)`. 

The use case case for this: Lazy people can just start with all functionality available without caring.

**Comment by artnerdnet** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#61: Create plugin that loads all plugins](https://trello.com/c/wAgnauwA/40-61-create-plugin-that-loads-all-plugins)
